FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
LABEL authors="damian"

RUN apt-get update && apt-get install -y git
RUN printf "tzdata tzdata/Areas select Europe\ntzdata tzdata/Zones/Europe select Vienna\n" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive apt-get install tzdata

RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
# Set root password for SSH access
RUN echo 'root:audiocraftui' | chpasswd
RUN sed -ri 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
EXPOSE 22

COPY ./requirements.txt /install/requirements.txt
RUN pip install -r /install/requirements.txt

WORKDIR /workspace
# automatically invalidate the cache when the repo changes
ADD https://api.github.com/repos/damian0815/audiocraft/git/refs/heads/token_build_progress /.git-hashref
RUN git clone https://github.com/damian0815/audiocraft && \
    cd audiocraft && \
    git checkout token_build_progress && \
    pip install -e . \

WORKDIR /workspace/audiocraftui
COPY app.py .
COPY backend .

EXPOSE 4000
#ENTRYPOINT ["flask", "run", "--port", "4000", "--host", "0.0.0.0", "--debug"]
ENTRYPOINT service ssh restart && flask run --port 4000 --host 0.0.0.0 --debug
